/* GENERATED by scripts/usage-map.mjs — do not edit by hand.
 *
 * Regenerate with `pnpm usage:map` after adding or re-wiring a template.
 * See the header of that script for why this is generated rather than written.
 */
export interface UsageRow {
  group: string
  name: string
  templates: string[]
}

/** Every shared element, most-reused first. */
export const USAGE: UsageRow[] = [
  {
    "group": "layout",
    "name": "SlideFrame",
    "templates": [
      "Agenda",
      "Bullets + Image",
      "Chart + Stats",
      "Chart Duo",
      "Chart Hero",
      "Chart Stack",
      "Closing",
      "Column Grid",
      "Comparison",
      "Cover",
      "Data Grid",
      "Device Showcase",
      "Diagram",
      "Feature Cards",
      "Financial Table",
      "Full Bleed",
      "Headline + Chart",
      "Headline + Image",
      "KPI Board",
      "Logo Wall",
      "Numbers",
      "Pillars",
      "Process",
      "Quote",
      "Section Divider",
      "Staircase Cards",
      "Stat Grid",
      "Statement",
      "Team Grid",
      "Team Row",
      "Timeline",
      "Tint Table",
      "Use of Funds"
    ]
  },
  {
    "group": "layout",
    "name": "SlideHeading",
    "templates": [
      "Bullets + Image",
      "Chart + Stats",
      "Chart Duo",
      "Chart Hero",
      "Chart Stack",
      "Closing",
      "Column Grid",
      "Comparison",
      "Data Grid",
      "Device Showcase",
      "Diagram",
      "Feature Cards",
      "Financial Table",
      "Full Bleed",
      "Headline + Chart",
      "Headline + Image",
      "KPI Board",
      "Logo Wall",
      "Numbers",
      "Pillars",
      "Process",
      "Staircase Cards",
      "Stat Grid",
      "Team Grid",
      "Team Row",
      "Timeline",
      "Tint Table",
      "Use of Funds"
    ]
  },
  {
    "group": "text",
    "name": "AccentText",
    "templates": [
      "Agenda",
      "Chart Duo",
      "Comparison",
      "Cover",
      "Device Showcase",
      "Diagram",
      "Headline + Image",
      "Numbers",
      "Pillars",
      "Process",
      "Quote",
      "Section Divider",
      "Statement",
      "Timeline",
      "Use of Funds"
    ]
  },
  {
    "group": "brand",
    "name": "Icon",
    "templates": [
      "Column Grid",
      "Comparison",
      "Device Showcase",
      "Diagram",
      "KPI Board",
      "Pillars",
      "Process",
      "Quote",
      "Timeline"
    ]
  },
  {
    "group": "data",
    "name": "SlideChart",
    "templates": [
      "Chart + Stats",
      "Chart Duo",
      "Chart Hero",
      "Chart Stack",
      "Headline + Chart"
    ]
  },
  {
    "group": "brand",
    "name": "EpLogo",
    "templates": [
      "Diagram",
      "Statement"
    ]
  },
  {
    "group": "media",
    "name": "ImageMosaic",
    "templates": [
      "Bullets + Image",
      "Headline + Image"
    ]
  },
  {
    "group": "media",
    "name": "PersonCard",
    "templates": [
      "Team Grid",
      "Team Row"
    ]
  },
  {
    "group": "data",
    "name": "StatCard",
    "templates": [
      "Chart + Stats",
      "Stat Grid"
    ]
  },
  {
    "group": "brand",
    "name": "ArrowGlyph",
    "templates": [
      "Full Bleed"
    ]
  },
  {
    "group": "data",
    "name": "ArrowStatRow",
    "templates": [
      "Numbers"
    ]
  },
  {
    "group": "text",
    "name": "BulletList",
    "templates": [
      "Bullets + Image"
    ]
  },
  {
    "group": "data",
    "name": "CompareBars",
    "templates": [
      "Numbers"
    ]
  },
  {
    "group": "data",
    "name": "ComparisonBand",
    "templates": [
      "Comparison"
    ]
  },
  {
    "group": "data",
    "name": "DataTable",
    "templates": [
      "Tint Table"
    ]
  },
  {
    "group": "media",
    "name": "DeviceFrame",
    "templates": [
      "Device Showcase"
    ]
  },
  {
    "group": "data",
    "name": "FeatureCard",
    "templates": [
      "Feature Cards"
    ]
  },
  {
    "group": "data",
    "name": "FeatureCardLayout",
    "templates": [
      "Feature Cards"
    ]
  },
  {
    "group": "data",
    "name": "FinancialFormat",
    "templates": [
      "Financial Table"
    ]
  },
  {
    "group": "data",
    "name": "FinancialGrid",
    "templates": [
      "Financial Table"
    ]
  },
  {
    "group": "media",
    "name": "LogoGrid",
    "templates": [
      "Logo Wall"
    ]
  },
  {
    "group": "layout",
    "name": "OutlineCard",
    "templates": [
      "Closing"
    ]
  },
  {
    "group": "data",
    "name": "StaircaseCard",
    "templates": [
      "Staircase Cards"
    ]
  },
  {
    "group": "data",
    "name": "StaticGrid",
    "templates": [
      "Data Grid"
    ]
  }
]

/** How many templates exist, for the "used by N of M" denominator. */
export const TEMPLATE_COUNT = 33
