/* Generates src/css/tokens.generated.css from src/tokens/*.js.
 *
 * The JS modules are the source of truth because the PPTX emitter needs
 * numeric values, not CSS strings — keeping a hand-written stylesheet in
 * sync would drift. Run via `pnpm build:tokens` (also wired as a prebuild
 * step); the output is committed so a fresh clone can run Storybook
 * without a generate step.
 */
import { writeFileSync, mkdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'
import { palette } from '../src/tokens/palette.js'
import { canvas, grid, type, gradient, tableTint, color, radius, space, shadow } from '../src/tokens/tokens.js'

const here = dirname(fileURLToPath(import.meta.url))
const out = resolve(here, '../src/css/tokens.generated.css')

/** camelCase / numeric key → kebab-case CSS ident. */
const kebab = (s) => String(s).replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase()
const px = (n) => (typeof n === 'number' ? `${+n.toFixed(4)}px` : n)

const lines = []
const section = (title) => lines.push('', `  /* ${'-'.repeat(66)}`, `   * ${title}`, `   * ${'-'.repeat(66)} */`)
const decl = (name, value) => lines.push(`  --${name}: ${value};`)

lines.push(
  '/* AUTO-GENERATED by scripts/build-tokens.mjs — do not edit by hand.',
  ' * Edit src/tokens/palette.js or src/tokens/tokens.js and re-run',
  ' * `pnpm build:tokens`.',
  ' *',
  ' * Every length is px inside the 1280x720 slide coordinate space, where',
  ' * 1px === 1/96in — exactly PowerPoint / Google Slides 16:9 geometry.',
  ' */',
  ':root {'
)

section('Tier 1 — primitive ramps (documentation + Colors story only)')
for (const [ramp, steps] of Object.entries(palette)) {
  lines.push(`  /* ${kebab(ramp)} */`)
  for (const [step, hex] of Object.entries(steps)) decl(`color-${kebab(ramp)}-${step}`, hex)
}

section('Canvas geometry')
decl('slide-width', px(canvas.width))
decl('slide-height', px(canvas.height))

section('Layout grid')
for (const [k, v] of Object.entries(grid)) decl(`slide-grid-${kebab(k)}`, typeof v === 'number' ? px(v) : v)

section('Typography')
decl('slide-font-family', type.fontFamily)
for (const [k, v] of Object.entries(type.weights)) decl(`slide-font-weight-${kebab(k)}`, v)
for (const [name, s] of Object.entries(type.scale)) {
  const n = kebab(name)
  decl(`slide-text-${n}-size`, px(s.size))
  decl(`slide-text-${n}-line-height`, s.lineHeight)
  decl(`slide-text-${n}-weight`, s.weight)
  decl(`slide-text-${n}-tracking`, s.tracking)
}

section('Semantic color')
for (const [k, v] of Object.entries(color)) {
  if (Array.isArray(v)) v.forEach((hex, i) => decl(`slide-color-${kebab(k)}-${i + 1}`, hex))
  else decl(`slide-color-${kebab(k)}`, v)
}

section('Brand gradients')
for (const [k, g] of Object.entries(gradient)) {
  decl(`slide-gradient-${kebab(k)}`, `linear-gradient(${g.angle}deg, ${g.from} 0%, ${g.to} 100%)`)
}

section('Tinted table ramp')
decl('slide-table-header', tableTint.header)
decl('slide-table-header-text', tableTint.headerText)
tableTint.rows.forEach((hex, i) => decl(`slide-table-row-${i + 1}`, hex))

section('Radii')
for (const [k, v] of Object.entries(radius)) decl(`slide-radius-${kebab(k)}`, px(v))

section('Spacing')
for (const [k, v] of Object.entries(space)) decl(`slide-space-${k}`, px(v))

section('Elevation')
for (const [k, v] of Object.entries(shadow)) decl(`slide-shadow-${kebab(k)}`, v)

lines.push('}', '')

mkdirSync(dirname(out), { recursive: true })
writeFileSync(out, lines.join('\n'), 'utf8')
console.log(`✓ wrote ${out} (${lines.length} lines)`)
