/* Builds the element→template usage map that the Components/Overview page renders.
 *
 *   node scripts/usage-map.mjs          # write src/stories/components/_usage.ts
 *   node scripts/usage-map.mjs --print  # just show it
 *
 * WHY GENERATED RATHER THAN HAND-WRITTEN: the whole point of the page is to be
 * trustworthy about what is shared. A hand-maintained list is wrong the first
 * time someone adds a template and forgets to update it, and a usage map that is
 * quietly wrong is worse than none — it is the thing you would consult before
 * changing a shared component, so being out of date is exactly the failure that
 * matters.
 *
 * It parses `import ... from '<path>'` in every template. That is a deliberate
 * simplification: it captures what a template DEPENDS on, which is the question
 * a style-guide edit asks ("if I change StatCard, what moves?"). It does not
 * count how many times a component is instantiated inside one template, and it
 * would miss a component reached dynamically — neither of which happens here.
 */
import { readFileSync, writeFileSync, readdirSync } from 'node:fs'
import { resolve, dirname, basename } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const TEMPLATES = resolve(root, 'src/templates')

/** 'Headline + Chart' from 'HeadlineChart' — matches the story titles. */
const LABELS = {
  BulletImage: 'Bullets + Image',
  HeadlineChart: 'Headline + Chart',
  HeadlineImage: 'Headline + Image',
  ChartStats: 'Chart + Stats',
  DataGridSlide: 'Data Grid',
  KpiBoard: 'KPI Board',
  UseOfFunds: 'Use of Funds',
}
const label = (n) => LABELS[n] ?? n.replace(/([a-z])([A-Z])/g, '$1 $2')

const files = readdirSync(TEMPLATES).filter((f) => f.endsWith('.tsx'))

/** element name → Set of template labels */
const uses = new Map()
/** template label → count of shared elements it pulls in */
const perTemplate = new Map()

for (const file of files) {
  const tpl = label(basename(file, '.tsx'))
  const src = readFileSync(resolve(TEMPLATES, file), 'utf8')
  const imports = [...src.matchAll(/import\s+\{([^}]+)\}\s+from\s+'(\.\.\/elements\/[^']+)'/g)]
  let n = 0
  for (const [, names, path] of imports) {
    const group = path.split('/')[2] // elements/<group>/<Name>
    for (const raw of names.split(',')) {
      const name = raw.trim().replace(/^type\s+/, '')
      // Skip type-only imports — a type is not a rendered component.
      if (!name || /^[a-z]/.test(name) || name.endsWith('Props') || name.endsWith('Spec')) continue
      const key = `${group}/${name}`
      if (!uses.has(key)) uses.set(key, new Set())
      uses.get(key).add(tpl)
      n++
    }
  }
  perTemplate.set(tpl, n)
}

const rows = [...uses.entries()]
  .map(([key, set]) => {
    const [group, name] = key.split('/')
    return { group, name, templates: [...set].sort() }
  })
  .sort((a, b) => b.templates.length - a.templates.length || a.name.localeCompare(b.name))

const out = `/* GENERATED by scripts/usage-map.mjs — do not edit by hand.
 *
 * Regenerate with \`pnpm usage:map\` after adding or re-wiring a template.
 * See the header of that script for why this is generated rather than written.
 */
export interface UsageRow {
  group: string
  name: string
  templates: string[]
}

/** Every shared element, most-reused first. */
export const USAGE: UsageRow[] = ${JSON.stringify(rows, null, 2)}

/** How many templates exist, for the "used by N of M" denominator. */
export const TEMPLATE_COUNT = ${files.length}
`

if (process.argv.includes('--print')) {
  for (const r of rows) console.log(String(r.templates.length).padStart(3), `${r.group}/${r.name}`)
  console.log(`\n${rows.length} shared elements across ${files.length} templates`)
} else {
  writeFileSync(resolve(root, 'src/stories/components/_usage.ts'), out)
  console.log(`✓ wrote src/stories/components/_usage.ts — ${rows.length} elements, ${files.length} templates`)
}
